module GitHub.Color exposing (colors)

import Dict exposing (Dict)


colors : Dict String (Maybe String)
colors =
    Dict.fromList
        [ ( "1C Enterprise", Just "#814CCC" )
        , ( "ABAP", Just "#E8274B" )
        , ( "ActionScript", Just "#882B0F" )
        , ( "Ada", Just "#02f88c" )
        , ( "Agda", Just "#315665" )
        , ( "AGS Script", Just "#B9D9FF" )
        , ( "Alloy", Just "#64C800" )
        , ( "Alpine Abuild", Nothing )
        , ( "AMPL", Just "#E6EFBB" )
        , ( "AngelScript", Just "#C7D7DC" )
        , ( "ANTLR", Just "#9DC3FF" )
        , ( "Apex", Nothing )
        , ( "API Blueprint", Just "#2ACCA8" )
        , ( "APL", Just "#5A8164" )
        , ( "Apollo Guidance Computer", Nothing )
        , ( "AppleScript", Just "#101F1F" )
        , ( "Arc", Just "#aa2afe" )
        , ( "ASP", Just "#6a40fd" )
        , ( "AspectJ", Just "#a957b0" )
        , ( "Assembly", Just "#6E4C13" )
        , ( "Asymptote", Just "#4a0c0c" )
        , ( "ATS", Just "#1ac620" )
        , ( "Augeas", Nothing )
        , ( "AutoHotkey", Just "#6594b9" )
        , ( "AutoIt", Just "#1C3552" )
        , ( "Awk", Nothing )
        , ( "Ballerina", Just "#FF5000" )
        , ( "Batchfile", Just "#C1F12E" )
        , ( "Befunge", Nothing )
        , ( "Bison", Nothing )
        , ( "BitBake", Nothing )
        , ( "BlitzBasic", Nothing )
        , ( "BlitzMax", Just "#cd6400" )
        , ( "Bluespec", Nothing )
        , ( "Boo", Just "#d4bec1" )
        , ( "Brainfuck", Just "#2F2530" )
        , ( "Brightscript", Nothing )
        , ( "Bro", Nothing )
        , ( "C", Just "#555555" )
        , ( "C#", Just "#178600" )
        , ( "C++", Just "#f34b7d" )
        , ( "C2hs Haskell", Nothing )
        , ( "Cap'n Proto", Nothing )
        , ( "CartoCSS", Nothing )
        , ( "Ceylon", Just "#dfa535" )
        , ( "Chapel", Just "#8dc63f" )
        , ( "Charity", Nothing )
        , ( "ChucK", Nothing )
        , ( "Cirru", Just "#ccccff" )
        , ( "Clarion", Just "#db901e" )
        , ( "Clean", Just "#3F85AF" )
        , ( "Click", Just "#E4E6F3" )
        , ( "CLIPS", Nothing )
        , ( "Clojure", Just "#db5855" )
        , ( "CMake", Nothing )
        , ( "COBOL", Nothing )
        , ( "CoffeeScript", Just "#244776" )
        , ( "ColdFusion", Just "#ed2cd6" )
        , ( "ColdFusion CFC", Nothing )
        , ( "Common Lisp", Just "#3fb68b" )
        , ( "Common Workflow Language", Just "#B5314C" )
        , ( "Component Pascal", Just "#B0CE4E" )
        , ( "Cool", Nothing )
        , ( "Coq", Nothing )
        , ( "Crystal", Just "#000100" )
        , ( "Csound", Nothing )
        , ( "Csound Document", Nothing )
        , ( "Csound Score", Nothing )
        , ( "CSS", Just "#563d7c" )
        , ( "Cuda", Just "#3A4E3A" )
        , ( "CWeb", Nothing )
        , ( "Cycript", Nothing )
        , ( "Cython", Nothing )
        , ( "D", Just "#ba595e" )
        , ( "Dart", Just "#00B4AB" )
        , ( "DataWeave", Just "#003a52" )
        , ( "DIGITAL Command Language", Nothing )
        , ( "DM", Just "#447265" )
        , ( "Dockerfile", Just "#384d54" )
        , ( "Dogescript", Just "#cca760" )
        , ( "DTrace", Nothing )
        , ( "Dylan", Just "#6c616e" )
        , ( "E", Just "#ccce35" )
        , ( "eC", Just "#913960" )
        , ( "ECL", Just "#8a1267" )
        , ( "ECLiPSe", Nothing )
        , ( "Eiffel", Just "#946d57" )
        , ( "Elixir", Just "#6e4a7e" )
        , ( "Elm", Just "#60B5CC" )
        , ( "Emacs Lisp", Just "#c065db" )
        , ( "EmberScript", Just "#FFF4F3" )
        , ( "EQ", Just "#a78649" )
        , ( "Erlang", Just "#B83998" )
        , ( "F#", Just "#b845fc" )
        , ( "F*", Just "#572e30" )
        , ( "Factor", Just "#636746" )
        , ( "Fancy", Just "#7b9db4" )
        , ( "Fantom", Just "#14253c" )
        , ( "Filebench WML", Nothing )
        , ( "Filterscript", Nothing )
        , ( "fish", Nothing )
        , ( "FLUX", Just "#88ccff" )
        , ( "Forth", Just "#341708" )
        , ( "Fortran", Just "#4d41b1" )
        , ( "FreeMarker", Just "#0050b2" )
        , ( "Frege", Just "#00cafe" )
        , ( "Game Maker Language", Just "#71b417" )
        , ( "GAMS", Nothing )
        , ( "GAP", Nothing )
        , ( "GCC Machine Description", Nothing )
        , ( "GDB", Nothing )
        , ( "GDScript", Just "#355570" )
        , ( "Genie", Just "#fb855d" )
        , ( "Genshi", Nothing )
        , ( "Gentoo Ebuild", Nothing )
        , ( "Gentoo Eclass", Nothing )
        , ( "Gherkin", Just "#5B2063" )
        , ( "GLSL", Nothing )
        , ( "Glyph", Just "#c1ac7f" )
        , ( "Gnuplot", Just "#f0a9f0" )
        , ( "Go", Just "#00ADD8" )
        , ( "Golo", Just "#88562A" )
        , ( "Gosu", Just "#82937f" )
        , ( "Grace", Nothing )
        , ( "Grammatical Framework", Just "#79aa7a" )
        , ( "Groovy", Just "#e69f56" )
        , ( "Groovy Server Pages", Nothing )
        , ( "Hack", Just "#878787" )
        , ( "Harbour", Just "#0e60e3" )
        , ( "Haskell", Just "#5e5086" )
        , ( "Haxe", Just "#df7900" )
        , ( "HCL", Nothing )
        , ( "HiveQL", Just "#dce200" )
        , ( "HLSL", Nothing )
        , ( "HTML", Just "#e34c26" )
        , ( "Hy", Just "#7790B2" )
        , ( "HyPhy", Nothing )
        , ( "IDL", Just "#a3522f" )
        , ( "Idris", Just "#b30000" )
        , ( "IGOR Pro", Nothing )
        , ( "Inform 7", Nothing )
        , ( "Inno Setup", Nothing )
        , ( "Io", Just "#a9188d" )
        , ( "Ioke", Just "#078193" )
        , ( "Isabelle", Just "#FEFE00" )
        , ( "Isabelle ROOT", Nothing )
        , ( "J", Just "#9EEDFF" )
        , ( "Jasmin", Nothing )
        , ( "Java", Just "#b07219" )
        , ( "Java Server Pages", Nothing )
        , ( "JavaScript", Just "#f1e05a" )
        , ( "JFlex", Nothing )
        , ( "Jison", Nothing )
        , ( "Jison Lex", Nothing )
        , ( "Jolie", Just "#843179" )
        , ( "JSONiq", Just "#40d47e" )
        , ( "Jsonnet", Just "#0064bd" )
        , ( "JSX", Nothing )
        , ( "Julia", Just "#a270ba" )
        , ( "Jupyter Notebook", Just "#DA5B0B" )
        , ( "Kotlin", Just "#F18E33" )
        , ( "KRL", Just "#28430A" )
        , ( "LabVIEW", Nothing )
        , ( "Lasso", Just "#999999" )
        , ( "Lean", Nothing )
        , ( "Lex", Just "#DBCA00" )
        , ( "LFE", Just "#4C3023" )
        , ( "LilyPond", Nothing )
        , ( "Limbo", Nothing )
        , ( "Literate Agda", Nothing )
        , ( "Literate CoffeeScript", Nothing )
        , ( "Literate Haskell", Nothing )
        , ( "LiveScript", Just "#499886" )
        , ( "LLVM", Just "#185619" )
        , ( "Logos", Nothing )
        , ( "Logtalk", Nothing )
        , ( "LOLCODE", Just "#cc9900" )
        , ( "LookML", Just "#652B81" )
        , ( "LoomScript", Nothing )
        , ( "LSL", Just "#3d9970" )
        , ( "Lua", Just "#000080" )
        , ( "M", Nothing )
        , ( "M4", Nothing )
        , ( "M4Sugar", Nothing )
        , ( "Makefile", Just "#427819" )
        , ( "Mako", Nothing )
        , ( "Mask", Just "#f97732" )
        , ( "Mathematica", Nothing )
        , ( "MATLAB", Just "#e16737" )
        , ( "Max", Just "#c4a79c" )
        , ( "MAXScript", Just "#00a6a6" )
        , ( "mcfunction", Just "#E22837" )
        , ( "Mercury", Just "#ff2b2b" )
        , ( "Meson", Just "#007800" )
        , ( "Metal", Just "#8f14e9" )
        , ( "MiniD", Nothing )
        , ( "Mirah", Just "#c7a938" )
        , ( "Modelica", Nothing )
        , ( "Modula-2", Nothing )
        , ( "Modula-3", Just "#223388" )
        , ( "Module Management System", Nothing )
        , ( "Monkey", Nothing )
        , ( "Moocode", Nothing )
        , ( "MoonScript", Nothing )
        , ( "MQL4", Just "#62A8D6" )
        , ( "MQL5", Just "#4A76B8" )
        , ( "MTML", Just "#b7e1f4" )
        , ( "MUF", Nothing )
        , ( "mupad", Nothing )
        , ( "Myghty", Nothing )
        , ( "NCL", Just "#28431f" )
        , ( "Nearley", Just "#990000" )
        , ( "Nemerle", Just "#3d3c6e" )
        , ( "nesC", Just "#94B0C7" )
        , ( "NetLinx", Just "#0aa0ff" )
        , ( "NetLinx+ERB", Just "#747faa" )
        , ( "NetLogo", Just "#ff6375" )
        , ( "NewLisp", Just "#87AED7" )
        , ( "Nextflow", Just "#3ac486" )
        , ( "Nim", Just "#37775b" )
        , ( "Nit", Just "#009917" )
        , ( "Nix", Just "#7e7eff" )
        , ( "NSIS", Nothing )
        , ( "Nu", Just "#c9df40" )
        , ( "NumPy", Nothing )
        , ( "Objective-C", Just "#438eff" )
        , ( "Objective-C++", Just "#6866fb" )
        , ( "Objective-J", Just "#ff0c5a" )
        , ( "OCaml", Just "#3be133" )
        , ( "Omgrofl", Just "#cabbff" )
        , ( "ooc", Just "#b0b77e" )
        , ( "Opa", Nothing )
        , ( "Opal", Just "#f7ede0" )
        , ( "OpenCL", Nothing )
        , ( "OpenEdge ABL", Nothing )
        , ( "OpenRC runscript", Nothing )
        , ( "OpenSCAD", Nothing )
        , ( "Ox", Nothing )
        , ( "Oxygene", Just "#cdd0e3" )
        , ( "Oz", Just "#fab738" )
        , ( "P4", Just "#7055b5" )
        , ( "Pan", Just "#cc0000" )
        , ( "Papyrus", Just "#6600cc" )
        , ( "Parrot", Just "#f3ca0a" )
        , ( "Parrot Assembly", Nothing )
        , ( "Parrot Internal Representation", Nothing )
        , ( "Pascal", Just "#E3F171" )
        , ( "Pawn", Just "#dbb284" )
        , ( "Pep8", Just "#C76F5B" )
        , ( "Perl", Just "#0298c3" )
        , ( "Perl 6", Just "#0000fb" )
        , ( "PHP", Just "#4F5D95" )
        , ( "PicoLisp", Nothing )
        , ( "PigLatin", Just "#fcd7de" )
        , ( "Pike", Just "#005390" )
        , ( "PLpgSQL", Nothing )
        , ( "PLSQL", Just "#dad8d8" )
        , ( "PogoScript", Just "#d80074" )
        , ( "Pony", Nothing )
        , ( "PostScript", Just "#da291c" )
        , ( "POV-Ray SDL", Nothing )
        , ( "PowerBuilder", Just "#8f0f8d" )
        , ( "PowerShell", Just "#012456" )
        , ( "Processing", Just "#0096D8" )
        , ( "Prolog", Just "#74283c" )
        , ( "Propeller Spin", Just "#7fa2a7" )
        , ( "Puppet", Just "#302B6D" )
        , ( "PureBasic", Just "#5a6986" )
        , ( "PureScript", Just "#1D222D" )
        , ( "Python", Just "#3572A5" )
        , ( "Python console", Nothing )
        , ( "q", Just "#0040cd" )
        , ( "QMake", Nothing )
        , ( "QML", Just "#44a51c" )
        , ( "Quake", Just "#882233" )
        , ( "R", Just "#198CE7" )
        , ( "Racket", Just "#3c5caa" )
        , ( "Ragel", Just "#9d5200" )
        , ( "RAML", Just "#77d9fb" )
        , ( "Rascal", Just "#fffaa0" )
        , ( "REALbasic", Nothing )
        , ( "Reason", Nothing )
        , ( "Rebol", Just "#358a5b" )
        , ( "Red", Just "#f50000" )
        , ( "Redcode", Nothing )
        , ( "Ren'Py", Just "#ff7f7f" )
        , ( "RenderScript", Nothing )
        , ( "REXX", Nothing )
        , ( "Ring", Just "#2D54CB" )
        , ( "RobotFramework", Nothing )
        , ( "Roff", Just "#ecdebe" )
        , ( "Rouge", Just "#cc0088" )
        , ( "RPC", Nothing )
        , ( "Ruby", Just "#701516" )
        , ( "RUNOFF", Just "#665a4e" )
        , ( "Rust", Just "#dea584" )
        , ( "Sage", Nothing )
        , ( "SaltStack", Just "#646464" )
        , ( "SAS", Just "#B34936" )
        , ( "Scala", Just "#c22d40" )
        , ( "Scheme", Just "#1e4aec" )
        , ( "Scilab", Nothing )
        , ( "sed", Just "#64b970" )
        , ( "Self", Just "#0579aa" )
        , ( "ShaderLab", Nothing )
        , ( "Shell", Just "#89e051" )
        , ( "ShellSession", Nothing )
        , ( "Shen", Just "#120F14" )
        , ( "Slash", Just "#007eff" )
        , ( "Slice", Just "#003fa2" )
        , ( "Smali", Nothing )
        , ( "Smalltalk", Just "#596706" )
        , ( "Smarty", Nothing )
        , ( "SMT", Nothing )
        , ( "Solidity", Just "#AA6746" )
        , ( "SourcePawn", Just "#5c7611" )
        , ( "SQF", Just "#3F3F3F" )
        , ( "SQLPL", Nothing )
        , ( "Squirrel", Just "#800000" )
        , ( "SRecode Template", Just "#348a34" )
        , ( "Stan", Just "#b2011d" )
        , ( "Standard ML", Just "#dc566d" )
        , ( "Stata", Nothing )
        , ( "SuperCollider", Just "#46390b" )
        , ( "Swift", Just "#ffac45" )
        , ( "SystemVerilog", Just "#DAE1C2" )
        , ( "Tcl", Just "#e4cc98" )
        , ( "Tcsh", Nothing )
        , ( "Terra", Just "#00004c" )
        , ( "TeX", Just "#3D6117" )
        , ( "Thrift", Nothing )
        , ( "TI Program", Just "#A0AA87" )
        , ( "TLA", Nothing )
        , ( "Turing", Just "#cf142b" )
        , ( "TXL", Nothing )
        , ( "TypeScript", Just "#2b7489" )
        , ( "Unified Parallel C", Nothing )
        , ( "Unix Assembly", Nothing )
        , ( "Uno", Nothing )
        , ( "UnrealScript", Just "#a54c4d" )
        , ( "UrWeb", Nothing )
        , ( "Vala", Just "#fbe5cd" )
        , ( "VCL", Just "#148AA8" )
        , ( "Verilog", Just "#b2b7f8" )
        , ( "VHDL", Just "#adb2cb" )
        , ( "Vim script", Just "#199f4b" )
        , ( "Visual Basic", Just "#945db7" )
        , ( "Volt", Just "#1F1F1F" )
        , ( "Vue", Just "#2c3e50" )
        , ( "wdl", Just "#42f1f4" )
        , ( "WebAssembly", Just "#04133b" )
        , ( "WebIDL", Nothing )
        , ( "wisp", Just "#7582D1" )
        , ( "X10", Just "#4B6BEF" )
        , ( "xBase", Just "#403a40" )
        , ( "XC", Just "#99DA07" )
        , ( "Xojo", Nothing )
        , ( "XProc", Nothing )
        , ( "XQuery", Just "#5232e7" )
        , ( "XS", Nothing )
        , ( "XSLT", Just "#EB8CEB" )
        , ( "Xtend", Nothing )
        , ( "Yacc", Just "#4B6C4B" )
        , ( "YARA", Just "#220000" )
        , ( "YASnippet", Just "#32AB90" )
        , ( "ZAP", Just "#0d665e" )
        , ( "Zephir", Just "#118f9e" )
        , ( "Zig", Just "#ec915c" )
        , ( "ZIL", Just "#dc75e5" )
        , ( "Zimpl", Nothing )
        ]
